# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.7', '3.10']

    steps:

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python packages
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run pycodestyle
        run: |
          pycodestyle src/*.py

      - name: Install python yaml package
        run: |
          pip install pyyaml

      - name: Run basic yaml validation
        run: |
          python tests/validate_yaml.py
  on-fail:
    if: failure()
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Add label to PR
        uses: actions/github-script@v7
        with:
          script: |
            const label = 'staging-skip';
            const { context, github } = require('@actions/github');
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pull_number = context.payload.pull_request.number;

            await github.issues.addLabels({
              owner,
              repo,
              issue_number: pull_number,
              labels: [label]
            });
